services:
  postgres:
    image: postgres:latest
    container_name: db-postgres
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
      - .env.development
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '${PGADMIN_PORT}:80'
    env_file:
      - .env
      - .env.development
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
      - .env.development
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
